name: myworkflow
on: 
   workflow_dispatch:
jobs:
    my-first-job:
        runs-on: ubuntu-latest
        steps:
           - name: checkout repo
             uses: actions/checkout@v3
           - name: run linux command
             run: |
                ls -lrt
                echo "Hello world -- myworkfrom"
           - name: run python script
             run: python abc.py     

             